package POTS;

import javax.swing.JOptionPane;

/**
 *
 * @author Saniah
 */
public class Administrator extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    public Administrator() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accessusersbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        registeruserbtn = new javax.swing.JButton();
        viewusersbtn = new javax.swing.JButton();
        deleteuserbtn = new javax.swing.JButton();
        updateuserdetailsbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accessusersbtn.setBackground(new java.awt.Color(153, 153, 153));
        accessusersbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accessusersbtn.setForeground(new java.awt.Color(255, 255, 255));
        accessusersbtn.setText("Access Users");
        accessusersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessusersbtnActionPerformed(evt);
            }
        });
        getContentPane().add(accessusersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 216, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 78, 150, 42));

        registeruserbtn.setBackground(new java.awt.Color(153, 153, 153));
        registeruserbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registeruserbtn.setForeground(new java.awt.Color(255, 255, 255));
        registeruserbtn.setText("Register User");
        registeruserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeruserbtnActionPerformed(evt);
            }
        });
        getContentPane().add(registeruserbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 216, 38));

        viewusersbtn.setBackground(new java.awt.Color(153, 153, 153));
        viewusersbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewusersbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewusersbtn.setText("View Users");
        viewusersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewusersbtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewusersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 216, 38));

        deleteuserbtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteuserbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteuserbtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteuserbtn.setText("Delete User");
        deleteuserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuserbtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteuserbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 216, 40));

        updateuserdetailsbtn.setBackground(new java.awt.Color(153, 153, 153));
        updateuserdetailsbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateuserdetailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        updateuserdetailsbtn.setText("Update User Details");
        updateuserdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateuserdetailsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateuserdetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 216, 40));

        logoutbtn.setBackground(new java.awt.Color(255, 204, 0));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.setActionCommand("jButton4");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrator");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 295, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTS/ad,pic (1).jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accessusersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessusersbtnActionPerformed
        // Prompt the admin to choose a user type
        String[] userTypes = {"Sales Manager", "Inventory Manager", "Requisition Manager", "Finance Manager"};
        String selection = (String) JOptionPane.showInputDialog(
            this,
            "Select which user form to access:",
            "Access Users",
            JOptionPane.QUESTION_MESSAGE,
            null,
            userTypes,
            userTypes[0] // Default selection
    );
        
        // Open the corresponding form based on selection
    if (selection != null) {
        switch (selection) {
            case "Sales Manager":
                new SalesManager().setVisible(true);
                break;
            case "Inventory Manager":
                new InventoryManager().setVisible(true);
                break;
            case "Purchase Manager":
                new PurchaseManager().setVisible(true);
                break;
            case "Finance Manager":
                new FinanceManager().setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Invalid selection!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose(); // Close the current form
    }
        
    }//GEN-LAST:event_accessusersbtnActionPerformed

    private void registeruserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeruserbtnActionPerformed
        try {
            new RegisterUser().setVisible(true); // Open RegisterUser form
            this.dispose(); // Close current form
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error while opening Register User form: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registeruserbtnActionPerformed

    private void viewusersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewusersbtnActionPerformed

        try {
            new ViewUsers().setVisible(true); // Open ViewUsers form
            this.dispose(); // Close current form
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error while opening View Users form: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewusersbtnActionPerformed

    private void deleteuserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuserbtnActionPerformed
        try {
            new DeleteUser().setVisible(true); // Open DeleteUser form
            this.dispose(); // Close current form
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error while opening Delete User form: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteuserbtnActionPerformed

    private void updateuserdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateuserdetailsbtnActionPerformed
        try {
            new UpdateUserDetails().setVisible(true); // Open UpdateUserDetails form
            this.dispose(); // Close current form
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error while opening Update User Details form: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateuserdetailsbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();//closing the current form
            new MainMenu().setVisible(true);//opening the MainMenu form
    }//GEN-LAST:event_logoutbtnActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessusersbtn;
    private javax.swing.JButton deleteuserbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton registeruserbtn;
    private javax.swing.JButton updateuserdetailsbtn;
    private javax.swing.JButton viewusersbtn;
    // End of variables declaration//GEN-END:variables
}
