package POTS;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Frame;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class PurchaseManager extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseManager
     */
    public PurchaseManager() {
        initComponents();
        hideTable(); 
    }
    
    private void hideTable() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_viewitems = new javax.swing.JButton();
        btn_po = new javax.swing.JButton();
        btn_requisitions = new javax.swing.JButton();
        btn_generatepo = new javax.swing.JButton();
        btn_viewsupplers = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewitems.setBackground(new java.awt.Color(153, 153, 153));
        btn_viewitems.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_viewitems.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewitems.setText("View Items");
        btn_viewitems.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_viewitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewitemsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 201, 38));

        btn_po.setBackground(new java.awt.Color(153, 153, 153));
        btn_po.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_po.setForeground(new java.awt.Color(255, 255, 255));
        btn_po.setText("View Purchase Orders");
        btn_po.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_poActionPerformed(evt);
            }
        });
        getContentPane().add(btn_po, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 201, 37));

        btn_requisitions.setBackground(new java.awt.Color(153, 153, 153));
        btn_requisitions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_requisitions.setForeground(new java.awt.Color(255, 255, 255));
        btn_requisitions.setText("Requistions");
        btn_requisitions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_requisitions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_requisitionsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_requisitions, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 201, 37));

        btn_generatepo.setBackground(new java.awt.Color(153, 153, 153));
        btn_generatepo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_generatepo.setForeground(new java.awt.Color(255, 255, 255));
        btn_generatepo.setText("Generate Purchase Order");
        btn_generatepo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_generatepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generatepoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_generatepo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 201, 38));

        btn_viewsupplers.setBackground(new java.awt.Color(153, 153, 153));
        btn_viewsupplers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_viewsupplers.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewsupplers.setText("View Suppliers");
        btn_viewsupplers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_viewsupplers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewsupplersActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewsupplers, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 390, 201, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 201, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Purchase Manager");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 368, -1));

        logoutbtn.setBackground(new java.awt.Color(255, 204, 0));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutbtn.setText("logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 19, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTS/manager,h_400,q_80,w_640 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewitemsActionPerformed

        // Create a dialog box
        JDialog itemDialog = new JDialog((Frame) null, "View Items", true);
        itemDialog.setSize(500, 400);
        itemDialog.setLayout(new BorderLayout());
        itemDialog.setLocationRelativeTo(null);

        // Create a table model
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Item Code");
        tableModel.addColumn("Item Name");
        tableModel.addColumn("Supplier ID");

        // Change file path to "managertxt.txt"
        String filePath = "managertxt.txt"; // Updated file path

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            boolean readItems = false;

            while ((line = br.readLine()) != null) {
                line = line.trim();

                // Detect the start of the Item Data section
                if (line.equalsIgnoreCase("# Item Data")) {
                    readItems = true;
                    br.readLine(); // Skip the header line (Item Code, Item Name, Supplier ID)
                    continue;
                }

                // Stop reading when the delimiter line for Item Data is encountered
                if (readItems && line.startsWith("------------------------------------------------------")) {
                    break;
                }

                // Read and process lines within the "Item Data" section
                if (readItems && !line.isEmpty()) {
                    String[] data = line.split(",\\s*");
                    if (data.length == 3) { // Ensure valid data (Item Code, Item Name, Supplier ID)
                        tableModel.addRow(data);
                    }
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error reading file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create the table and add it to a scroll pane
        JTable itemTable = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(itemTable);

        // Create a small Close button
        JButton closeButton = new JButton("Close");
        closeButton.setPreferredSize(new Dimension(80, 30)); // Set small size
        closeButton.addActionListener(e -> itemDialog.dispose());

        // Add the button to a panel for proper alignment
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(closeButton);

        // Add components to the dialog
        itemDialog.add(scrollPane, BorderLayout.CENTER);
        itemDialog.add(buttonPanel, BorderLayout.SOUTH);

        // Show the dialog
        itemDialog.setVisible(true);

    }//GEN-LAST:event_btn_viewitemsActionPerformed

    private void btn_poActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_poActionPerformed

        // Create a dialog box to display user registration data
        JDialog poDialog = new JDialog((Frame) null, "View Purchase Orders", true);
poDialog.setSize(500, 400);
poDialog.setLayout(new BorderLayout());
poDialog.setLocationRelativeTo(null);

// Create a table model for Purchase Order Data
DefaultTableModel tableModel = new DefaultTableModel();
tableModel.addColumn("PO ID");
tableModel.addColumn("Item Code");
tableModel.addColumn("Date");
tableModel.addColumn("Status");

// Change file path to "PurchaseOrder.txt"
String filePath = "PurchaseOrder.txt"; // Updated file path
boolean readPoData = false;

try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
    String line;

    // Read file line by line
    while ((line = br.readLine()) != null) {
        line = line.trim();

        // Detect the start of the Purchase Order Data section
        if (line.equalsIgnoreCase("# Purchase Order (PO) Data")) {
            readPoData = true;
            br.readLine(); // Skip the header line (PO ID, Item_Code, Date, Status)
            continue;
        }

        // Stop reading when the delimiter line is encountered
        if (readPoData && line.startsWith("------------------------------------------------------------")) {
            break; // End of the Purchase Order data section
        }

        // Read and process lines within the Purchase Order section
        if (readPoData && !line.isEmpty()) {
            String[] data = line.split(",\\s*"); // Split the line by comma and optional space
            if (data.length == 4) { // Ensure we have 4 elements (PO ID, Item Code, Date, Status)
                tableModel.addRow(data); // Add row to the table model
            }
        }
    }
} catch (IOException ex) {
    JOptionPane.showMessageDialog(null, "Error reading file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Create the table and add it to a scroll pane
JTable poTable = new JTable(tableModel);
JScrollPane scrollPane = new JScrollPane(poTable);

// Create a small Close button
JButton closeButton = new JButton("Close");
closeButton.setPreferredSize(new Dimension(80, 30)); // Set small size
closeButton.addActionListener(e -> poDialog.dispose());

// Add the button to a panel for proper alignment
JPanel buttonPanel = new JPanel();
buttonPanel.add(closeButton);

// Add components to the dialog
poDialog.add(scrollPane, BorderLayout.CENTER);
poDialog.add(buttonPanel, BorderLayout.SOUTH);

// Show the dialog
poDialog.setVisible(true);


    }//GEN-LAST:event_btn_poActionPerformed

    private void btn_requisitionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_requisitionsActionPerformed

        // Hide the current frame
        this.setVisible(false);  // Hide the current frame

        // Create and display the PurschaseManager JFrame
        Requisition_PM requisitionFrame = new Requisition_PM();
        requisitionFrame.setVisible(true);  // Set the frame to be visible

    }//GEN-LAST:event_btn_requisitionsActionPerformed

    private void btn_generatepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generatepoActionPerformed

        // Hide the current frame
        this.setVisible(false);

        // Create and display the PurchaseOrder JFrame
        PurchaseOrder purchaseOrderFrame = new PurchaseOrder();
        purchaseOrderFrame.setVisible(true);  // Set the frame to be visible

    }//GEN-LAST:event_btn_generatepoActionPerformed

    private void btn_viewsupplersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewsupplersActionPerformed

        // Create a dialog box to display Supplier data
        JDialog supplierDialog = new JDialog((Frame) null, "View Suppliers", true);
        supplierDialog.setSize(500, 400);
        supplierDialog.setLayout(new BorderLayout());
        supplierDialog.setLocationRelativeTo(null);

        // Create a table model for Supplier Data
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Supplier ID");
        tableModel.addColumn("Supplier Name");
        tableModel.addColumn("Item Supplied");

        // Change file path to "managertxt.txt"
        String filePath = "managertxt.txt"; // Updated file path
        boolean readSuppliers = false;

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;

            // Read file line by line
            while ((line = br.readLine()) != null) {
                line = line.trim();

                // Detect the start of the Supplier Data section
                if (line.equalsIgnoreCase("# Supplier Data")) {
                    readSuppliers = true;
                    br.readLine(); // Skip the header line (Supplier ID, Supplier Name, Item Supplied)
                    continue;
                }

                // Stop reading when the delimiter line is encountered
                if (readSuppliers && line.startsWith("------------------------------------------------------------")) {
                    break; // End of the Supplier data section
                }

                // Read and process lines within the Supplier Data section
                if (readSuppliers && !line.isEmpty()) {
                    // Split the line by commas and spaces, while keeping the supplier name intact
                    String[] data = line.split(",\\s*"); // Split by commas followed by any number of spaces
                    if (data.length == 3) { // Ensure we have 3 elements (Supplier ID, Supplier Name, Item Supplied)
                        tableModel.addRow(data); // Add row to the table model
                    }
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error reading file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create the table and add it to a scroll pane
        JTable supplierTable = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(supplierTable);

        // Create a small Close button
        JButton closeButton = new JButton("Close");
        closeButton.setPreferredSize(new Dimension(80, 30)); // Set small size
        closeButton.addActionListener(e -> supplierDialog.dispose());

        // Add the button to a panel for proper alignment
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(closeButton);

        // Add components to the dialog
        supplierDialog.add(scrollPane, BorderLayout.CENTER);
        supplierDialog.add(buttonPanel, BorderLayout.SOUTH);

        // Show the dialog
        supplierDialog.setVisible(true);

    }//GEN-LAST:event_btn_viewsupplersActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        this.dispose();//closing the current form
        new MainMenu().setVisible(true);//opening the MainMenu form
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generatepo;
    private javax.swing.JButton btn_po;
    private javax.swing.JButton btn_requisitions;
    private javax.swing.JButton btn_viewitems;
    private javax.swing.JButton btn_viewsupplers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutbtn;
    // End of variables declaration//GEN-END:variables
}
