package POTS;


public class Requisition_PM extends javax.swing.JFrame {

    /**
     * Creates new form Requisition_PM
     */
    public Requisition_PM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_close = new javax.swing.JButton();
        btn_create = new javax.swing.JButton();
        btn_viewall = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Req = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_close.setBackground(new java.awt.Color(255, 204, 0));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_create.setBackground(new java.awt.Color(153, 153, 153));
        btn_create.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_create.setForeground(new java.awt.Color(255, 255, 255));
        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        btn_viewall.setBackground(new java.awt.Color(153, 153, 153));
        btn_viewall.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_viewall.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewall.setText("View All");
        btn_viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewallActionPerformed(evt);
            }
        });

        tbl_Req.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PR ID", "Sales Manager", "Quantity", "Date", "Priority"
            }
        ));
        jScrollPane2.setViewportView(tbl_Req);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Requistions");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTS/monitor (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btn_viewall, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // Dispose the current frame (Requisition or PurchaseOrder)
        this.dispose();

        // Create and show the PurschaseManager JFrame again
        PurchaseManager managerFrame = new PurchaseManager();
        managerFrame.setVisible(true);  // Show PurschaseManager
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed

        // Create a new dialog for requisition entry
javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Create New Requisition", true);
dialog.setSize(500, 300);
dialog.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

// Components for item selection
dialog.add(new javax.swing.JLabel("Select Item:"));
javax.swing.JComboBox<String> itemComboBox = new javax.swing.JComboBox<>(new String[]{
    "102/Microwave Oven",
    "104/Washing Machine",
    "105/Ceiling Fan",
    "103/LED Television",
    "109/Air Conditioner",
    "110/LED Light Bulbs",
    "101/Electrical Kettle",
    "106/Refrigerator",
    "108/Rice Cooker",
    "107/Bluetooth Speaker"
});
dialog.add(itemComboBox);

// Components for quantity input
dialog.add(new javax.swing.JLabel("Quantity Required:"));
javax.swing.JTextField quantityField = new javax.swing.JTextField();
dialog.add(quantityField);

// Components for date input
dialog.add(new javax.swing.JLabel("Required By Date (yyyy-MM-dd):"));
javax.swing.JTextField dateField = new javax.swing.JTextField();
dialog.add(dateField);

// Components for priority selection
dialog.add(new javax.swing.JLabel("Priority:"));
javax.swing.JComboBox<String> priorityComboBox = new javax.swing.JComboBox<>(new String[]{
    "Low", "Medium", "High"
});
dialog.add(priorityComboBox);

// Submit button
javax.swing.JButton submitButton = new javax.swing.JButton("Submit");
submitButton.addActionListener(e -> {
    // Retrieve entered values
    String selectedItem = (String) itemComboBox.getSelectedItem();
    String[] itemDetails = selectedItem.split("/");
    String itemCode = itemDetails[0];
    String itemName = itemDetails[1];
    String quantity = quantityField.getText();
    String requiredDate = dateField.getText();
    String priority = (String) priorityComboBox.getSelectedItem();

    // Validate input
    if (quantity.isEmpty() || requiredDate.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(dialog, "Please fill all fields.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Path to the file (relative path)
    String filePath = "PurchaseRequisition.txt";

    try {
        // Read the current contents of the file
        java.nio.file.Path path = java.nio.file.Paths.get(filePath);
        java.util.List<String> lines = java.nio.file.Files.readAllLines(path);

        // Variable to track if the separator was found
        boolean separatorFound = false;
        StringBuilder newContent = new StringBuilder();

        // Process each line to find the separator and append data
        for (String line : lines) {
            newContent.append(line).append("\n");
            if (line.contains("------------------------------------------------------------")) {
                separatorFound = true;
                newContent.append(itemCode).append(", ").append(itemName).append(", ").append(quantity).append(", ")
                          .append(requiredDate).append(", ").append(priority).append("\n");
            }
        }

        // If the separator is not found, notify the user
        if (!separatorFound) {
            javax.swing.JOptionPane.showMessageDialog(dialog, "The required separator was not found in the file.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Write the updated content back to the file
        java.nio.file.Files.write(path, newContent.toString().getBytes());

        javax.swing.JOptionPane.showMessageDialog(dialog, "Requisition saved successfully.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Update the JTable with the new requisition data
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbl_Req.getModel();
        model.addRow(new Object[]{itemCode, itemName, quantity, requiredDate, priority});
        dialog.dispose(); // Close the dialog

    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(dialog, "Error saving requisition: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
});

dialog.add(submitButton);

// Cancel button
javax.swing.JButton cancelButton = new javax.swing.JButton("Cancel");
cancelButton.addActionListener(e -> dialog.dispose());
dialog.add(cancelButton);

// Show the dialog
dialog.setVisible(true);


    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewallActionPerformed

        // File path for the text file (relative path to your program)
        String filePath = "PurchaseRequisition.txt";

        try {
            // Read all lines from the file
            java.nio.file.Path path = java.nio.file.Paths.get(filePath);
            java.util.List<String> lines = java.nio.file.Files.readAllLines(path);

            // Create a table model to populate the JTable
            javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel();

            // Skip comment lines, divider lines, or empty lines
            boolean isFirstLine = true;

            // Loop through the lines and process them
            for (int i = 0; i < lines.size(); i++) {
                String line = lines.get(i).trim();

                // Skip comment lines, divider lines, or empty lines
                if (line.startsWith("#") || line.startsWith("-") || line.isEmpty()) {
                    continue;
                }

                // Skip the first line (which is the column headers)
                if (isFirstLine) {
                    // Add column headers from the first data line
                    String[] headers = line.split(",\\s*");
                    for (String header : headers) {
                        tableModel.addColumn(header); // Add each column header dynamically
                    }
                    isFirstLine = false;
                    continue;
                }

                // Split the line into columns by comma (and trim whitespace)
                String[] columns = line.split(",\\s*");

                // Check if the line has the correct number of columns
                if (columns.length == 5) {
                    // Handle PR ID if needed, split into two parts if it includes a description
                    String[] prIdParts = columns[0].split("/");
                    columns[0] = prIdParts[0];  // PR ID part
                    String prDescription = prIdParts.length > 1 ? prIdParts[1] : ""; // PR Description if exists

                    // Optionally, you can add PR description as a new column or process differently.
                    System.out.println("PR Description: " + prDescription); // Log if needed

                    // Add the data row to the table model
                    tableModel.addRow(columns);
                } else {
                    // Log malformed line
                    System.err.println("Skipping malformed line: " + line);
                }
            }

            // Set the table model for tbl_Req
            tbl_Req.setModel(tableModel);

        } catch (java.io.IOException ex) {
            // Handle exceptions if file not found or other IO issues
            javax.swing.JOptionPane.showMessageDialog(this, "Error reading file: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            // Catch any other exceptions
            javax.swing.JOptionPane.showMessageDialog(this, "Unexpected error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_viewallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requisition_PM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requisition_PM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requisition_PM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requisition_PM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Requisition_PM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_viewall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Req;
    // End of variables declaration//GEN-END:variables
}
