/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package POTS;

/**
 *
 * @author Saniah
 */
public class SalesManager extends javax.swing.JFrame {

    /**
     * Creates new form SalesManager
     */
    public SalesManager() {
        setTitle("Sales Manager Menu");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ViewPurchaserBTN = new javax.swing.JButton();
        ViewItemsBTN = new javax.swing.JButton();
        StockLevelBTN = new javax.swing.JButton();
        DailyBTN = new javax.swing.JButton();
        RequisitionBTN = new javax.swing.JButton();
        ReportBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtn.setBackground(new java.awt.Color(255, 204, 0));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 103, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sales Manager Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 17, 334, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 76, 130, -1));

        ViewPurchaserBTN.setBackground(new java.awt.Color(153, 153, 153));
        ViewPurchaserBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewPurchaserBTN.setForeground(new java.awt.Color(255, 255, 255));
        ViewPurchaserBTN.setText("View Purchaser Orders");
        ViewPurchaserBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPurchaserBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ViewPurchaserBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 183, 195, 40));

        ViewItemsBTN.setBackground(new java.awt.Color(153, 153, 153));
        ViewItemsBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewItemsBTN.setForeground(new java.awt.Color(255, 255, 255));
        ViewItemsBTN.setText("View Items");
        ViewItemsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewItemsBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ViewItemsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 235, 195, 40));

        StockLevelBTN.setBackground(new java.awt.Color(153, 153, 153));
        StockLevelBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StockLevelBTN.setForeground(new java.awt.Color(255, 255, 255));
        StockLevelBTN.setText("Stock Level");
        StockLevelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockLevelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(StockLevelBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 287, 195, 36));

        DailyBTN.setBackground(new java.awt.Color(153, 153, 153));
        DailyBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DailyBTN.setForeground(new java.awt.Color(255, 255, 255));
        DailyBTN.setText("Daily Item-wise Sales Entry");
        DailyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyBTNActionPerformed(evt);
            }
        });
        getContentPane().add(DailyBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 335, 195, 38));

        RequisitionBTN.setBackground(new java.awt.Color(153, 153, 153));
        RequisitionBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequisitionBTN.setForeground(new java.awt.Color(255, 255, 255));
        RequisitionBTN.setText("Create Requisition");
        RequisitionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequisitionBTNActionPerformed(evt);
            }
        });
        getContentPane().add(RequisitionBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 385, 195, 39));

        ReportBTN.setBackground(new java.awt.Color(153, 153, 153));
        ReportBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ReportBTN.setForeground(new java.awt.Color(255, 255, 255));
        ReportBTN.setText("Sales Report");
        ReportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ReportBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 136, 195, 35));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTS/sale,m.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewPurchaserBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPurchaserBTNActionPerformed
        // TODO add your handling code here:
        ViewPurchaserForm vpf = new ViewPurchaserForm();
        vpf.show();

        dispose();
    }//GEN-LAST:event_ViewPurchaserBTNActionPerformed

    private void ViewItemsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewItemsBTNActionPerformed
        // TODO add your handling code here:
        ViewItemsForm vif = new ViewItemsForm();
        vif.show();

        dispose();
    }//GEN-LAST:event_ViewItemsBTNActionPerformed

    private void StockLevelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockLevelBTNActionPerformed
        // TODO add your handling code here:
        StockLevel sl = new StockLevel();
        sl.show();

        dispose();
    }//GEN-LAST:event_StockLevelBTNActionPerformed

    private void DailyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyBTNActionPerformed
        // TODO add your handling code here:
        TotalSalesEntry dse = new TotalSalesEntry();
        dse.show();

        dispose();
    }//GEN-LAST:event_DailyBTNActionPerformed

    private void RequisitionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequisitionBTNActionPerformed
        // TODO add your handling code here:
        Requisition rst = new Requisition();
        rst.show();

        dispose();
    }//GEN-LAST:event_RequisitionBTNActionPerformed

    private void ReportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBTNActionPerformed
        // TODO add your handling code here:
        SalesReport sp = new SalesReport();
        sp.show();

        dispose();
    }//GEN-LAST:event_ReportBTNActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        this.dispose();//closing the current form
        new MainMenu().setVisible(true);//opening the MainMenu form
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DailyBTN;
    private javax.swing.JButton ReportBTN;
    private javax.swing.JButton RequisitionBTN;
    private javax.swing.JButton StockLevelBTN;
    private javax.swing.JButton ViewItemsBTN;
    private javax.swing.JButton ViewPurchaserBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutbtn;
    // End of variables declaration//GEN-END:variables
}
